export type Styles = {
  button: string;
  button__content: string;
  "button__content--disabled": string;
  "button__content--loading": string;
  button__icon: string;
  "button__icon--left": string;
  "button__icon--on-left": string;
  "button__icon--right": string;
  button__loader: string;
  "button__loading-floating-border": string;
  button_primary: string;
  button_primary__icon: string;
  button_primary__icon_left: string;
  button_primary__icon_right: string;
  button_primary_invert: string;
  button_primary_large: string;
  button_primary_medium: string;
  "button--auto-size": string;
  "button--danger": string;
  "button--dark": string;
  "button--extra-small": string;
  "button--full-width": string;
  "button--gradient": string;
  "button--info": string;
  "button--inverted": string;
  "button--large": string;
  "button--light": string;
  "button--link": string;
  "button--loading": string;
  "button--medium": string;
  "button--outlined": string;
  "button--primary": string;
  "button--secondary": string;
  "button--small": string;
  "button--success": string;
  "button--text": string;
  "button-outline": string;
  "button-outline__icon": string;
  "button-outline_inverse": string;
  "button-outline_inverse-thin": string;
  "button-outline_large": string;
  "button-outline_medium": string;
  "button-outline--large": string;
  "button-outline--medium": string;
  home: string;
  "home__button-box": string;
  home__intro: string;
  "home__intro--box": string;
  "home__intro--cta": string;
  "home__intro--headline": string;
  "home__intro--image": string;
  "home__intro--linear-gradient": string;
  "home__intro--text-block": string;
  home__metamask: string;
  "home__no-claim": string;
  "home__no-claim--warning": string;
  "home__property-card--cta": string;
  "home__property-card--row": string;
  spin: string;
  "z-depth-0": string;
  "z-depth-1": string;
  "z-depth-1-half": string;
  "z-depth-2": string;
  "z-depth-3": string;
  "z-depth-4": string;
  "z-depth-5": string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
