export const VIEW_METHODS = [
  "get_market_data",
  "get_pricing_data",
  "get_resolution_data",
  "get_fee_ratio",
  "get_outcome_token",
  "get_outcome_ids",
  "get_block_timestamp",
  "get_collateral_token_metadata",
  "get_market_creator_account_id",
  "dao_account_id",
  "resolution_window",
  "resolved_at",
  "is_resolved",
  "get_buy_sell_timestamp",
  "is_open",
  "is_closed",
  "is_over",
  "is_resolution_window_expired",
  "balance_of",
  "get_amount_mintable",
  "get_amount_payable",
  "get_precision_decimals",
  "calc_percentage",
];

export const CHANGE_METHODS = ["buy", "sell", "new", "aggregator_read"];
