export const VIEW_METHODS = [
  "get_market_data",
  "get_resolution_data",
  "get_fee_data",
  "get_management_data",
  "get_collateral_token_metadata",
  "get_outcome_token",
  "get_outcome_ids",
  "get_block_timestamp",
  "resolved_at",
  "get_buy_sell_timestamp",
  "balance_of",
  "get_amount_mintable",
  "get_amount_payable_unresolved",
  "get_amount_payable_resolved",
  "get_precision_decimals",
  "calc_percentage",
  "is_resolved",
  "is_open",
  "is_over",
  "is_reveal_window_expired",
  "is_resolution_window_expired",
  "is_expired_unresolved",
  "is_claiming_window_expired",
];

export const CHANGE_METHODS = ["sell", "reveal", "resolve"];
